import {
  GitLabIcon,
  CodePenIcon,
  CodewarsIcon,
  DevToIcon,
  FacebookIcon,
  FrontendMentorIcon,
  GithubIcon,
  HashnodeIcon,
  LinkedinIcon,
  StackOverflowIcon,
  TwitchIcon,
  TwitterIcon,
  YoutubeIcon,
  FreeCodeCampLogoIcon,
} from "@/components/icons/link-icons";

const linkOptions = [
  {
    id: 1,
    label: "Github",
    value: "github",
    icon: GithubIcon,
    color: "#1A1A1A",
  },
  {
    id: 2,
    label: "Youtube",
    value: "youtube",
    icon: YoutubeIcon,
    color: "#EE3939",
  },
  {
    id: 3,
    label: "Linkedin",
    value: "linkedin",
    icon: LinkedinIcon,
    color: "#2D68FF",
  },
  {
    id: 4,
    label: "Facebook",
    value: "facebook",
    icon: FacebookIcon,
    color: "#2442AC",
  },
  {
    id: 5,
    label: "Frontend Mentor",
    value: "frontend-mentor",
    icon: FrontendMentorIcon,
    color: "#FFFFFF",
  },
  {
    id: 6,
    label: "Hashnode",
    value: "hashnode",
    icon: HashnodeIcon,
    color: "#0330D1",
  },
  {
    id: 7,
    label: "Twitter",
    value: "twitter",
    icon: TwitterIcon,
    color: "#43B7E9",
  },
  {
    id: 8,
    label: "Twitch",
    value: "twitch",
    icon: TwitchIcon,
    color: "#EE3FC8",
  },
  {
    id: 9,
    label: "Dev.to",
    value: "dev-to",
    icon: DevToIcon,
    color: "#333333",
  },
  {
    id: 10,
    label: "Codewars",
    value: "codewars",
    icon: CodewarsIcon,
    color: "#8A1A50",
  },
  {
    id: 11,
    label: "Codepen",
    value: "codepen",
    icon: CodePenIcon,
    color: "#47CF73",
  },
  {
    id: 12,
    label: "freeCodeCamp",
    value: "free-code-camp",
    icon: FreeCodeCampLogoIcon,
    color: "#302267",
  },
  {
    id: 13,
    label: "Gitlab",
    value: "gitlab",
    icon: GitLabIcon,
    color: "#EB4925",
  },
  {
    id: 14,
    label: "Stack Overflow",
    value: "stack-overflow",
    icon: StackOverflowIcon,
    color: "#EC7100",
  },
];

export default linkOptions;
